export enum HttpStatus {
  Ok = 200,
  Created = 201,
  BadRequest = 400,
  Unauthorized = 401,
  Forbidden = 403,
  NotFound = 404,
  MethodNotAllowed = 405,
  RequestTimeout = 408,
  Conflict = 409,
  UnprocessableEntity = 422,
  TooManyRequests = 429,
  InternalServerError = 500,
  NotImplemented = 501,
  ServiceUnavailable = 503,
}

export const HttpStatusMessages: Record<HttpStatus, string> = {
  [HttpStatus.Ok]: "OK",
  [HttpStatus.Created]: "Created",
  [HttpStatus.BadRequest]: "Bad Request",
  [HttpStatus.Unauthorized]: "Unauthorized",
  [HttpStatus.Forbidden]: "Forbidden",
  [HttpStatus.NotFound]: "Not Found",
  [HttpStatus.MethodNotAllowed]: "Method Not Allowed",
  [HttpStatus.RequestTimeout]: "Request Timeout",
  [HttpStatus.Conflict]: "Conflict",
  [HttpStatus.UnprocessableEntity]: "Unprocessable Entity",
  [HttpStatus.TooManyRequests]: "Too Many Requests",
  [HttpStatus.InternalServerError]: "Internal Server Error",
  [HttpStatus.NotImplemented]: "Not Implemented",
  [HttpStatus.ServiceUnavailable]: "Service Unavailable",
} as const;
